global using System;
global using System.Net;
global using System.Data;
global using System.Linq;
global using System.Text;
global using System.Text.Json;
global using System.Reflection;
global using System.Diagnostics;
global using System.Globalization;
global using System.ComponentModel;
global using System.Buffers.Binary;
global using System.Threading.Tasks;
global using System.Security.Claims;
global using System.Text.Encodings.Web;
global using System.Collections.Generic;
global using System.Security.Cryptography;
global using System.Collections.Concurrent;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;

global using Polly;
global using MediatR;
global using Polly.Caching;
global using Newtonsoft.Json;
global using FluentValidation;
global using Ardalis.GuardClauses;
global using FluentValidation.Results;
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.Logging;
global using Newtonsoft.Json.Serialization;
global using Microsoft.Extensions.Caching.Memory;

global using JsonException = System.Text.Json.JsonException;
global using JsonSerializer = System.Text.Json.JsonSerializer;
global using JsonConverterNet = System.Text.Json.Serialization;
