USE HR;

-- Foreign keys.
ALTER TABLE HR.TBL_USER_TOKENS ADD CONSTRAINT USR_CRED_FK FOREIGN KEY (credential_id) REFERENCES HR.TBL_USERS(credential_id);
ALTER TABLE HR.TBL_MODULE_POLICY ADD CONSTRAINT POLICY_FK FOREIGN KEY (module_id) REFERENCES HR.TBL_MODULES(module_id);
ALTER TABLE HR.TBL_MODULE_POLICY ADD CONSTRAINT MODULE_FK FOREIGN KEY (policy_Id) REFERENCES HR.TBL_POLICIES(policy_id);
ALTER TABLE HR.TBL_USERS_MODULE_POLICY ADD CONSTRAINT USR_MOD_POL_FK FOREIGN KEY (credential_id) REFERENCES HR.TBL_USERS(credential_id);
ALTER TABLE HR.TBL_USERS_MODULE_POLICY ADD CONSTRAINT MOD_POL_FK FOREIGN KEY (module_policy_id) REFERENCES HR.TBL_MODULE_POLICY(module_policy_id);
ALTER TABLE HR.TBL_USERS_PARAMETERS ADD CONSTRAINT USR_PAR_FK FOREIGN KEY (credential_id) REFERENCES HR.TBL_USERS(credential_id);
ALTER TABLE HR.TBL_USERS_PARAMETERS ADD CONSTRAINT PAR_USR_FK FOREIGN KEY (parameter_id) REFERENCES HR.TBL_PARAMETERS(parameter_id);
ALTER TABLE HR.TBL_COUNTRIES ADD CONSTRAINT COUNTRY_REG_FK FOREIGN KEY (region_id) REFERENCES HR.TBL_REGIONS(region_id);
ALTER TABLE HR.TBL_LOCATIONS ADD CONSTRAINT LOC_C_ID_FK FOREIGN KEY (country_id) REFERENCES HR.TBL_COUNTRIES(country_id);
ALTER TABLE HR.TBL_DEPARTMENTS ADD CONSTRAINT DEPT_LOC_FK FOREIGN KEY (location_id) REFERENCES HR.TBL_LOCATIONS (location_id);
ALTER TABLE HR.TBL_JOB_HISTORY ADD CONSTRAINT JOB_HIS_EMP_PK FOREIGN KEY (employee_id) REFERENCES HR.TBL_EMPLOYEES (employee_id);
ALTER TABLE HR.TBL_JOB_HISTORY ADD CONSTRAINT JOB_HIS_JOB_PK FOREIGN KEY (job_id) REFERENCES HR.TBL_JOBS (job_id);
ALTER TABLE HR.TBL_JOB_HISTORY ADD CONSTRAINT JOB_HIS_DEPT_PK FOREIGN KEY (department_id) REFERENCES HR.TBL_DEPARTMENTS (department_id);
ALTER TABLE HR.TBL_DEPARTMENTS ADD CONSTRAINT DEPT_MGR_FK FOREIGN KEY (manager_id) REFERENCES HR.TBL_EMPLOYEES (employee_id) ON DELETE SET NULL ON UPDATE CASCADE;

COMMIT;